-- Additive Identity support. Review before applying to any existing database.
-- Prerequisite: the exact supplied 37-table InviteMe baseline.
ALTER TABLE inviteme.users
    ADD COLUMN user_name VARCHAR(256),
    ADD COLUMN normalized_user_name VARCHAR(256),
    ADD COLUMN normalized_email VARCHAR(256),
    ADD COLUMN email_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN security_stamp TEXT,
    ADD COLUMN concurrency_stamp TEXT,
    ADD COLUMN phone_number_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN lockout_end TIMESTAMPTZ,
    ADD COLUMN lockout_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN access_failed_count INTEGER NOT NULL DEFAULT 0;

-- Existing password_hash values are preserved; compatibility must be verified.
UPDATE inviteme.users
SET user_name = email,
    normalized_user_name = UPPER(email),
    normalized_email = UPPER(email),
    security_stamp = gen_random_uuid()::text,
    concurrency_stamp = gen_random_uuid()::text;

CREATE UNIQUE INDEX uq_users_normalized_user_name ON inviteme.users(normalized_user_name);
CREATE INDEX ix_users_normalized_email ON inviteme.users(normalized_email);

ALTER TABLE inviteme.roles
    ADD COLUMN normalized_name VARCHAR(256),
    ADD COLUMN concurrency_stamp TEXT;
UPDATE inviteme.roles SET normalized_name = UPPER(code), concurrency_stamp = gen_random_uuid()::text;
CREATE UNIQUE INDEX uq_roles_normalized_name ON inviteme.roles(normalized_name);

-- UUID user/role keys remain unchanged. Standard Identity claim row IDs are integers;
-- provider login/token records use their standard composite keys.
CREATE TABLE inviteme.user_claims (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    claim_type TEXT,
    claim_value TEXT,
    CONSTRAINT fk_user_claims_user FOREIGN KEY (user_id) REFERENCES inviteme.users(id) ON DELETE CASCADE
);
CREATE INDEX ix_user_claims_user_id ON inviteme.user_claims(user_id);

CREATE TABLE inviteme.role_claims (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id UUID NOT NULL,
    claim_type TEXT,
    claim_value TEXT,
    CONSTRAINT fk_role_claims_role FOREIGN KEY (role_id) REFERENCES inviteme.roles(id) ON DELETE CASCADE
);
CREATE INDEX ix_role_claims_role_id ON inviteme.role_claims(role_id);

CREATE TABLE inviteme.user_logins (
    login_provider VARCHAR(128) NOT NULL,
    provider_key VARCHAR(128) NOT NULL,
    provider_display_name TEXT,
    user_id UUID NOT NULL,
    PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT fk_user_logins_user FOREIGN KEY (user_id) REFERENCES inviteme.users(id) ON DELETE CASCADE
);
CREATE INDEX ix_user_logins_user_id ON inviteme.user_logins(user_id);

CREATE TABLE inviteme.user_tokens (
    user_id UUID NOT NULL,
    login_provider VARCHAR(128) NOT NULL,
    name VARCHAR(128) NOT NULL,
    value TEXT,
    PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT fk_user_tokens_user FOREIGN KEY (user_id) REFERENCES inviteme.users(id) ON DELETE CASCADE
);

-- EF relationship indexes not present in the supplied DDL.
CREATE INDEX ix_user_roles_role_id ON inviteme.user_roles(role_id);
CREATE INDEX ix_role_permissions_permission_id ON inviteme.role_permissions(permission_id);
CREATE INDEX ix_wedding_member_permissions_permission_id ON inviteme.wedding_member_permissions(permission_id);

-- The baseline functions use unqualified table references. Pin their execution schema
-- so app connections with the normal PostgreSQL search_path work correctly.
ALTER FUNCTION inviteme.set_updated_at() SET search_path = inviteme, pg_temp;
ALTER FUNCTION inviteme.validate_seating_assignment() SET search_path = inviteme, pg_temp;
ALTER FUNCTION inviteme.validate_guest_group_scope() SET search_path = inviteme, pg_temp;
ALTER FUNCTION inviteme.validate_event_venue_scope() SET search_path = inviteme, pg_temp;
ALTER FUNCTION inviteme.validate_invitation_scope() SET search_path = inviteme, pg_temp;
ALTER FUNCTION inviteme.validate_waitlist_scope() SET search_path = inviteme, pg_temp;
ALTER FUNCTION inviteme.validate_checkin_scope() SET search_path = inviteme, pg_temp;
ALTER FUNCTION inviteme.validate_gift_scope() SET search_path = inviteme, pg_temp;
