<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>inviteme-api-development</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../InviteMe.Application/InviteMe.Application.csproj" />
    <ProjectReference Include="../InviteMe.Infrastructure/InviteMe.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>
</Project>
